Feat/movie info display
katjones23/N2Movies pull request #12
Opened 2020-04-16 01:11 UTC by Isaiahpkelly

created the modals to display movie info also changed the search bar text to white

2020-04-16 21:18 UTC, katjones23 requested changes

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<script src="https://code.jquery.com/jquery-3.4.1.min.js"
Should be at the bottom of body, above the Materialize CDN

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<link rel="stylesheet" href="./index.css">
Should be inside the head

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<script src="./index.js"></script>
Should be last script tag inside the body

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on index.js
>    $(document).ready(function(){
This is in the JS file twice (first instance at the top).  Can we remove one of them?

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
Should be second script tag (below Jquery) inside the body

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
89-90: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +          <h5 class="white-text">Footer Content</h5>
88-89: we can get other opinions as well, but I don't think we need any text here.

2020-04-16 21:18 UTC, katjones23 commented on 404page.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on action.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on animation.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on comedy.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on drama.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on fantasy.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:18 UTC, katjones23 commented on romance.html
> +            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
Links: Trending and New Releases don't go anywhere; About Us maybe we can scrap since we don't have any content at this time?  Same for Link4.
Do we need links for our MVP?

2020-04-16 21:49 UTC, katjones23 commented on index.html
> +              <div id="modal1" class="modal">
all the modals have the same ID; can only have one item with the same ID.  All the pushes from JS would be the same across all cards

2020-04-17 01:38 UTC, Isaiahpkelly commented on index.html
> +              <div id="modal1" class="modal">
It was just a placeholder id

2020-04-17 04:11 UTC, closed without merging