Feat/trending section
katjones23/N2Movies pull request #6
Opened 2020-04-13 23:50 UTC by Isaiahpkelly

added the trending section.

2020-04-14 00:00 UTC, katjones23 requested changes
Script tag should be at the bottom of the body.

2020-04-14 00:41 UTC, katjones23 commented on index.html
>  <script src="./index.js"></script>
Script at the bottom of the body

2020-04-14 19:32 UTC, katjones23 approved these changes

2020-04-14 21:56 UTC, tmanderson001 approved these changes

2020-04-16 21:20 UTC, katjones23 commented on index.html
> +    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
Jquery should be the first script, then Materialize CDN, finally our JS file

2020-04-16 21:20 UTC, katjones23 commented on index.js
> +    alert('hi');
If testing is done, should remove this alert

2020-04-16 21:20 UTC, katjones23 commented on index.js
> +    alert('hi');
If testing is done, should remove this alert

2020-04-16 21:21 UTC, katjones23 requested changes
please see comments

2020-04-16 23:27 UTC, Isaiahpkelly commented on index.html
> +    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
Hey Katherine, I think we have been and fourth on this one. I have changed it both ways but believe we came to an agreement with Esterling on this way
![Screenshot (134)](https://user-images.githubusercontent.com/61264828/79516008-177f2380-8018-11ea-8ccd-9674a42ffd30.png)

2020-04-16 23:29 UTC, Isaiahpkelly commented on index.js
> +    alert('hi');
Will make sure I remove it going forward. It seems as if everything is already changed when I reopen the branch

2020-04-17 04:11 UTC, closed without merging